framework:
  messenger:
    transports:
      scheduler_default: '%env(MESSENGER_SCHEDULER_TRANSPORT_DSN)%'
    routing:
    default_bus: messenger.bus.default
    buses:
      messenger.bus.default: []